
'use strict';
const SUBJECTS={REG:'Regulamentação',MET:'Meteorologia',NAV:'Navegação',TV:'Teoria de Voo',CT:'Conhecimentos Técnicos'};
const NAME_TO_CODE=Object.fromEntries(Object.entries(SUBJECTS).map(([k,v])=>[v,k]));
const DB=(window.SEED_DATA&&window.SEED_DATA.questions)||[];
const K='ppa95_state_v1'; let state=load(); let currentSubject='REG',currentChapter='0',quiz=null;
function load(){try{return JSON.parse(localStorage.getItem(K))||fresh()}catch(e){return fresh()}}
function fresh(){return {schema:1,answers:[],errors:[],progress:{},settings:{},history:[],notes:{},customQuestions:[],createdAt:new Date().toISOString()}}
function save(){localStorage.setItem(K,JSON.stringify(state));renderProgress()}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));scrollTo(0,0);if(id==='progress')renderProgress();if(id==='flight')renderFlight()}
function codeOf(q){return NAME_TO_CODE[q.subject]||q.subject||''}
function pool(sub=null,ch=null){return DB.concat(state.customQuestions||[]).filter(q=>(!sub||codeOf(q)===sub)&& (ch===null||String(q.chapter)===String(ch)))}
function chapters(sub){let m=new Map();pool(sub).forEach(q=>m.set(String(q.chapter),q.topic||('Capítulo '+q.chapter)));return [...m.entries()].sort((a,b)=>String(a[0]).localeCompare(String(b[0]),undefined,{numeric:true}))}
function mastery(sub){let a=state.answers.filter(x=>!sub||x.subject===sub);return a.length?Math.round(100*a.filter(x=>x.correct).length/a.length):0}
function renderHome(){document.getElementById('today').textContent=new Intl.DateTimeFormat('pt-PT',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date());document.getElementById('gauges').innerHTML=Object.keys(SUBJECTS).map(s=>`<div class="gauge"><strong>${mastery(s)}%</strong><span>${s}</span></div>`).join('')}
function renderSubjects(){document.getElementById('subjectList').innerHTML=Object.entries(SUBJECTS).map(([s,n])=>`<div class="row" data-subject="${s}"><div class="grow"><b>${s} — ${n}</b><small>${pool(s).length} questões locais • ${chapters(s).length} grupos/capítulos no banco atual</small></div><span class="pill">${mastery(s)}%</span></div>`).join('')}
function openSubject(s){currentSubject=s;document.getElementById('chapterTitle').textContent=`${s} — ${SUBJECTS[s]}`;let cs=chapters(s);document.getElementById('chapterList').innerHTML=cs.map(([c,t])=>`<div class="row" data-chapter="${c}"><div class="grow"><b>Cap. ${c} — ${t}</b><small>${pool(s,c).length} questões disponíveis</small></div><span>›</span></div>`).join('')||'<div class="notice">Ainda não há questões classificadas nesta matéria.</div>';go('chapters')}
function openChapter(c){currentChapter=String(c);let qs=pool(currentSubject,currentChapter),topics=[...new Set(qs.map(q=>q.topic).filter(Boolean))];document.getElementById('studyTitle').textContent=`${currentSubject} • Cap. ${c}`;document.getElementById('studyBody').innerHTML=`<div class="studyBox"><div class="eyebrow">CONTEÚDO INDEXADO</div><h3>${topics[0]||'Capítulo '+c}</h3><p class="muted">Esta versão separa o motor da aplicação do banco de conteúdo. O treino abaixo usa somente questões existentes no banco local e preserva as respetivas explicações.</p><b>${qs.length}</b> questões disponíveis neste grupo.</div>`;go('study')}
function startQuiz(items,title){items=shuffle(items);if(!items.length){alert('Não há questões disponíveis para este treino.');return false}quiz={items,index:0,correct:0,answered:false,title};document.getElementById('quizTitle').textContent=title;go('quiz');renderQuestion();return true}
function renderQuestion(){let q=quiz.items[quiz.index];quiz.answered=false;document.getElementById('quizCount').textContent=`Questão ${quiz.index+1} de ${quiz.items.length}`;document.getElementById('quizScore').textContent=`Acertos: ${quiz.correct}`;document.getElementById('quizBar').style.width=`${100*quiz.index/quiz.items.length}%`;document.getElementById('qText').textContent=q.text;document.getElementById('options').innerHTML=q.options.map((o,i)=>`<button class="opt" data-option="${i}"><b>${'ABCD'[i]}.</b> ${o}</button>`).join('');document.getElementById('feedback').classList.add('hide');document.getElementById('nextBtn').classList.add('hide')}
function answer(i){if(!quiz||quiz.answered)return;quiz.answered=true;let q=quiz.items[quiz.index],ok=i===q.correctIndex;if(ok)quiz.correct++;state.answers.push({id:q.id,subject:codeOf(q),chapter:String(q.chapter),correct:ok,at:new Date().toISOString()});if(!ok)state.errors.push({id:q.id,subject:codeOf(q),chapter:String(q.chapter),at:new Date().toISOString()});save();document.querySelectorAll('.opt').forEach((b,n)=>{b.disabled=true;if(n===q.correctIndex)b.classList.add('correct');else if(n===i)b.classList.add('wrong')});let f=document.getElementById('feedback');f.textContent=(ok?'✓ Correto. ':'✗ Resposta incorreta. ')+(q.explanation||'');f.classList.remove('hide');document.getElementById('nextBtn').classList.remove('hide')}
function nextQuestion(){if(quiz.index+1>=quiz.items.length){let pct=Math.round(100*quiz.correct/quiz.items.length);state.history.push({title:quiz.title,score:pct,count:quiz.items.length,at:new Date().toISOString()});save();alert(`Treino concluído: ${pct}% (${quiz.correct}/${quiz.items.length})`);go('progress');return}quiz.index++;renderQuestion()}
function mixed(n){let arr=[];for(const s of Object.keys(SUBJECTS))arr.push(...shuffle(pool(s)).slice(0,Math.ceil(n/5)));return shuffle(arr).slice(0,n)}
function startSim(kind){if(kind==='mixed')startQuiz(mixed(20),'Simulado misto');if(kind==='full'){let a=[];Object.keys(SUBJECTS).forEach(s=>a.push(...shuffle(pool(s)).slice(0,20)));startQuiz(a,'Prova completa PPA')}if(kind==='errors'){let ids=new Set(state.errors.map(e=>e.id)),a=DB.filter(q=>ids.has(q.id));startQuiz(a.length?a:mixed(20),'Recuperação de erros')}}
function renderProgress(){let a=state.answers,c=a.filter(x=>x.correct).length,p=a.length?Math.round(100*c/a.length):0;document.getElementById('mastery').textContent=p+'%';document.getElementById('stats').innerHTML=`<p>Questões respondidas: <b>${a.length}</b></p><p>Corretas: <b>${c}</b></p><p>Erros registados: <b>${state.errors.length}</b></p><p>Simulados concluídos: <b>${state.history.length}</b></p>`;renderHome()}
function renderAI(){let s=document.getElementById('aiSubject');s.innerHTML=Object.entries(SUBJECTS).map(([k,v])=>`<option value="${k}">${k} — ${v}</option>`).join('');s.value=currentSubject;updateAIChapters()}
function updateAIChapters(){let s=document.getElementById('aiSubject').value,c=document.getElementById('aiChapter');c.innerHTML=chapters(s).map(([id,t])=>`<option value="${id}">Cap. ${id} — ${t}</option>`).join('')}
function generateQuestions(){let s=document.getElementById('aiSubject').value,c=document.getElementById('aiChapter').value,n=+document.getElementById('aiQty').value,a=shuffle(pool(s,c)).slice(0,n);document.getElementById('aiMsg').textContent=n>a.length?`Offline/local: encontrei ${a.length} questões neste grupo. Para criar questões realmente inéditas, será necessário configurar o endpoint seguro de IA.`:`Sessão local preparada com ${a.length} questões sem depender da Internet.`;if(a.length)startQuiz(a,`Treino gerado • ${s} ${c}`)}
function net(){let el=document.getElementById('net'),on=navigator.onLine;el.textContent=on?'● ONLINE':'✈ OFFLINE';el.className='status '+(on?'online':'offline')}
async function weather(){let icao=document.getElementById('icao').value.trim().toUpperCase();if(!/^[A-Z]{4}$/.test(icao)){return wx('ICAO inválido.','—',false)}let url=`https://aviationweather.gov/api/data/metar?ids=${encodeURIComponent(icao)}&format=raw&taf=false`;try{let r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);let t=(await r.text()).trim();if(!t)throw new Error('Sem METAR retornado');let obj={icao,raw:t,fetchedAt:new Date().toISOString()};localStorage.setItem('ppa95_wx_'+icao,JSON.stringify(obj));wx(`● AO VIVO • consulta ${new Date().toLocaleTimeString('pt-PT')}`,t,true)}catch(e){let c=localStorage.getItem('ppa95_wx_'+icao);if(c){let o=JSON.parse(c);wx(`✈ CACHE • última consulta online ${new Date(o.fetchedAt).toLocaleString('pt-PT')} • não é dado atual`,o.raw,false)}else wx('SEM DADOS • não foi possível obter METAR e não existe cache.',String(e.message||e),false)}}
function wx(msg,raw,live){let e=document.getElementById('wxState');e.textContent=msg;e.className='notice '+(live?'ok':'');document.getElementById('wxRaw').textContent=raw}
function renderFlight(){document.getElementById('offlineCount').textContent=DB.length+(state.customQuestions||[]).length;document.getElementById('offlineChecklist').innerHTML=['Interface da aplicação','Banco local de questões','Gabaritos e explicações','Progresso e erros','Simulados','E6B/recursos locais quando instalados'].map(x=>`<p>✓ ${x}</p>`).join('')}
async function prepareFlight(){if('serviceWorker'in navigator)await navigator.serviceWorker.ready.catch(()=>null);localStorage.setItem('ppa95_flight_ready',new Date().toISOString());let e=document.getElementById('flightMsg');e.textContent=`FLIGHT PACK — READY • ${DB.length} questões locais • preparado ${new Date().toLocaleString('pt-PT')}`;e.classList.remove('hide')}
function exportBackup(){let payload={product:'PPA ANAC 95+',schema:1,exportedAt:new Date().toISOString(),state};let blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`PPA95_Backup_${new Date().toISOString().slice(0,10)}.ppa`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);msgBackup('Backup exportado. Guarde o ficheiro fora do dispositivo.')}
function msgBackup(t){let e=document.getElementById('backupMsg');e.textContent=t;e.classList.remove('hide')}
async function importBackup(file){try{let x=JSON.parse(await file.text());if(x.product!=='PPA ANAC 95+'||!x.state||x.schema!==1)throw new Error('Backup incompatível ou inválido');let old=JSON.stringify(state);try{state=x.state;save();localStorage.setItem('ppa95_last_preimport',old)}catch(e){state=JSON.parse(old);throw e}msgBackup(`Backup restaurado: ${state.answers.length} respostas, ${state.errors.length} erros e ${state.history.length} simulados.`)}catch(e){msgBackup('Não foi possível restaurar: '+e.message)}}
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open('ppa95_files',1);r.onupgradeneeded=()=>r.result.createObjectStore('materials',{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function saveMaterial(){let fs=[...document.getElementById('materialFile').files];if(!fs.length)return document.getElementById('materialMsg').textContent='Selecione pelo menos um ficheiro.';try{let db=await openDB(),tx=db.transaction('materials','readwrite'),st=tx.objectStore('materials');for(const f of fs)st.put({id:crypto.randomUUID(),name:f.name,type:f.type,size:f.size,addedAt:new Date().toISOString(),blob:f});await new Promise((r,j)=>{tx.oncomplete=r;tx.onerror=()=>j(tx.error)});document.getElementById('materialMsg').textContent=`${fs.length} ficheiro(s) guardado(s) localmente. PDFs ficam preservados para indexação posterior.`}catch(e){document.getElementById('materialMsg').textContent='Erro ao guardar: '+e.message}}
function mission(){let weak=Object.keys(SUBJECTS).sort((a,b)=>mastery(a)-mastery(b))[0];startQuiz(shuffle(pool(weak)).slice(0,20),`Missão de hoje • ${weak}`)}
function bind(){document.addEventListener('click',e=>{let g=e.target.closest('[data-go]');if(g){go(g.dataset.go);if(g.dataset.go==='ai')renderAI();return}let s=e.target.closest('[data-subject]');if(s)return openSubject(s.dataset.subject);let c=e.target.closest('[data-chapter]');if(c)return openChapter(c.dataset.chapter);let o=e.target.closest('[data-option]');if(o)return answer(+o.dataset.option);let sim=e.target.closest('[data-sim]');if(sim)return startSim(sim.dataset.sim);let a=e.target.closest('[data-action]');if(!a)return;({mission,backChapters:()=>go('chapters'),chapterQuiz:()=>startQuiz(shuffle(pool(currentSubject,currentChapter)).slice(0,50),`${currentSubject} ${currentChapter} • 50`),chapterAI:()=>{go('ai');renderAI()},quitQuiz:()=>go('home'),nextQuestion,generateQuestions,weather,prepareFlight,exportBackup,saveMaterial}[a.dataset.action]||(()=>{}))()});document.getElementById('aiSubject').addEventListener('change',updateAIChapters);document.getElementById('backupFile').addEventListener('change',e=>e.target.files[0]&&importBackup(e.target.files[0]));addEventListener('online',net);addEventListener('offline',net)}
async function selfTest(){let tests=[];function t(name,fn){try{let v=fn();tests.push([name,!!v])}catch(e){tests.push([name,false,e.message])}}t('bank-loaded',()=>DB.length===1240);t('subjects',()=>Object.keys(SUBJECTS).every(s=>pool(s).length>0));t('shuffle',()=>shuffle([1,2,3]).length===3);t('mixed20',()=>mixed(20).length===20);t('full100',()=>Object.keys(SUBJECTS).every(s=>pool(s).length>=20));t('backup-schema',()=>fresh().schema===1);t('chapter-pool',()=>chapters('CT').length>0);let el=document.getElementById('selftest');el.classList.remove('hide');el.textContent='SELFTEST:'+JSON.stringify(tests);document.body.dataset.selftest=tests.every(x=>x[1])?'PASS':'FAIL'}
function init(){renderHome();renderSubjects();renderProgress();renderAI();net();bind();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(console.warn);if(new URLSearchParams(location.search).has('selftest'))selfTest()}
document.addEventListener('DOMContentLoaded',init);
