'use strict';
// Banco externo V16 — questões ORIGINAIS baseadas em conceitos públicos verificados.
// Não reproduz enunciados/alternativas da página-fonte. A página de origem declara foco em MMA;
// por isso entram no PPA apenas conceitos compatíveis com Teoria de Voo de asa fixa.
window.EXTERNAL_BANK_META={
  version:16,
  sourceName:'Hangar MMA — Simulado ANAC Aerodinâmica',
  sourceUrl:'https://hangarmma.com.br/blog/simulado-anac-aerodinamica/',
  checkedAt:'2026-09-18',
  sourceAudience:'Mecânico de Manutenção Aeronáutica (MMA)',
  ppaClassification:'TV — Teoria de Voo / Aerodinâmica e comandos de voo',
  importPolicy:'Somente conceitos de asa fixa compatíveis com PPA. Itens específicos de helicóptero, manutenção e conteúdo de alta velocidade não entram no simulado PPA padrão.',
  status:'Fonte externa não-oficial; a alegação de ocorrência em provas é da própria página e não é tratada pelo app como banco oficial ANAC.'
};
window.EXTERNAL_QUESTIONS=[
{id:'EXT-HMMA-TV-001',subject:'Teoria de Voo',chapter:'2',topic:'Aerofólio',text:'Em um perfil aerodinâmico, a cambra descreve principalmente:',options:['a curvatura do perfil','a distância entre as pontas das asas','o ângulo do eixo longitudinal com o horizonte','a espessura do revestimento'],correctIndex:0,explanation:'Cambra é a curvatura do perfil do aerofólio.',difficulty:2,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-002',subject:'Teoria de Voo',chapter:'3',topic:'Eficiência aerodinâmica',text:'Uma forma usual de representar a eficiência aerodinâmica de uma asa é pela relação entre:',options:['sustentação e arrasto','peso e potência','tração e peso','velocidade e altitude'],correctIndex:0,explanation:'A razão L/D compara sustentação gerada com arrasto produzido.',difficulty:2,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-003',subject:'Teoria de Voo',chapter:'4',topic:'Trim',text:'O principal objetivo de um compensador (trim) é:',options:['reduzir o esforço contínuo nos comandos','aumentar a potência do motor','substituir o aileron','eliminar o arrasto parasita'],correctIndex:0,explanation:'O compensador alivia esforços nos comandos e ajuda a manter uma atitude selecionada.',difficulty:2,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-004',subject:'Teoria de Voo',chapter:'3',topic:'Arrasto',text:'Em relação ao vento relativo, a força de arrasto atua:',options:['paralela e em sentido oposto','perpendicular e no mesmo sentido','paralela e no mesmo sentido','perpendicular e em sentido oposto'],correctIndex:0,explanation:'O arrasto é paralelo ao vento relativo e opõe-se ao movimento relativo da aeronave no ar.',difficulty:2,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-005',subject:'Teoria de Voo',chapter:'3',topic:'Sustentação',text:'A sustentação aerodinâmica é definida, idealmente, como uma força:',options:['perpendicular ao vento relativo','paralela ao vento relativo','sempre paralela ao horizonte','sempre alinhada ao eixo longitudinal'],correctIndex:0,explanation:'Por definição, a sustentação atua perpendicularmente ao vento relativo.',difficulty:2,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-006',subject:'Teoria de Voo',chapter:'2',topic:'Corda',text:'A linha reta imaginária que liga o bordo de ataque ao bordo de fuga de um aerofólio recebe o nome de:',options:['corda','envergadura','datum','diedro'],correctIndex:0,explanation:'A corda é a linha de referência entre os bordos de ataque e de fuga.',difficulty:1,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-007',subject:'Teoria de Voo',chapter:'4',topic:'Leme',text:'Qual superfície primária controla a guinada de um avião convencional?',options:['leme de direção','profundor','aileron','flape'],correctIndex:0,explanation:'A guinada ocorre em torno do eixo vertical e é controlada pelo leme de direção.',difficulty:1,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-008',subject:'Teoria de Voo',chapter:'4',topic:'Aileron',text:'Os ailerons são utilizados principalmente para controlar:',options:['o rolamento','a arfagem','a potência','a razão de mistura'],correctIndex:0,explanation:'Os ailerons controlam o rolamento em torno do eixo longitudinal.',difficulty:1,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-009',subject:'Teoria de Voo',chapter:'5',topic:'Estabilidade',text:'Em um avião convencional, a estabilidade direcional está associada principalmente à tendência de recuperar o alinhamento em torno do:',options:['eixo vertical','eixo longitudinal','eixo lateral','eixo da hélice'],correctIndex:0,explanation:'Estabilidade direcional relaciona-se à guinada, movimento em torno do eixo vertical.',difficulty:3,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-010',subject:'Teoria de Voo',chapter:'4',topic:'Comandos primários',text:'Qual conjunto contém somente comandos primários de voo de um avião convencional?',options:['ailerons, profundor e leme','flapes, slats e spoilers','trim, flapes e leme','ailerons, flapes e compensador'],correctIndex:0,explanation:'Ailerons, profundor e leme são os três comandos primários clássicos.',difficulty:2,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-011',subject:'Teoria de Voo',chapter:'4',topic:'Empenagem',text:'Na deriva de um avião convencional, a superfície móvel que comanda a guinada é o:',options:['leme de direção','estabilizador vertical','profundor','aileron'],correctIndex:0,explanation:'O estabilizador vertical é a parte fixa; o leme de direção é a superfície móvel.',difficulty:2,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-012',subject:'Teoria de Voo',chapter:'2',topic:'Ângulo de ataque',text:'O ângulo de ataque é medido entre a linha de corda do aerofólio e:',options:['a direção do vento relativo','o horizonte natural','o eixo vertical da aeronave','a direção do norte magnético'],correctIndex:0,explanation:'Ângulo de ataque é o ângulo entre a corda e o vento relativo.',difficulty:1,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-013',subject:'Teoria de Voo',chapter:'4',topic:'Batente',text:'Em um sistema de comandos, um batente mecânico tem por finalidade:',options:['limitar a deflexão máxima de uma superfície','aumentar a sustentação em baixa velocidade','compensar automaticamente a guinada','medir o ângulo de ataque'],correctIndex:0,explanation:'O batente impede que o comando ultrapasse o curso previsto.',difficulty:2,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-014',subject:'Teoria de Voo',chapter:'4',topic:'Eixos',text:'O eixo que atravessa a aeronave aproximadamente de baixo para cima é o:',options:['vertical','longitudinal','lateral','de incidência'],correctIndex:0,explanation:'O eixo vertical é a referência para o movimento de guinada.',difficulty:1,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-015',subject:'Teoria de Voo',chapter:'9',topic:'Derrapagem',text:'Numa curva descoordenada, quando a aeronave tende a deslocar-se lateralmente para fora da trajetória da curva, ocorre:',options:['derrapagem','glissagem','arfagem','rolamento coordenado'],correctIndex:0,explanation:'A derrapagem corresponde ao deslizamento lateral para o exterior da curva.',difficulty:3,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-016',subject:'Teoria de Voo',chapter:'9',topic:'Glissagem',text:'Quando o avião escorrega lateralmente para o interior da curva por falta de coordenação, a condição é chamada de:',options:['glissagem','derrapagem','guinada adversa','cabrada'],correctIndex:0,explanation:'Glissagem é o deslocamento lateral para o lado interno da curva.',difficulty:3,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-017',subject:'Teoria de Voo',chapter:'4',topic:'Pedais',text:'Nos aviões convencionais, o acionamento dos pedais movimenta principalmente:',options:['o leme de direção','os ailerons','o profundor','os flapes'],correctIndex:0,explanation:'Os pedais comandam o leme de direção e, em muitas aeronaves, também se associam ao controle direcional no solo.',difficulty:1,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-018',subject:'Teoria de Voo',chapter:'10',topic:'Hipersustentadores',text:'Flapes e dispositivos de bordo de ataque são usados principalmente para:',options:['permitir maior sustentação em velocidades mais baixas','eliminar totalmente o arrasto','aumentar a velocidade de estol','substituir os comandos primários'],correctIndex:0,explanation:'Dispositivos hipersustentadores aumentam a capacidade de sustentação em baixa velocidade.',difficulty:2,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-019',subject:'Teoria de Voo',chapter:'10',topic:'Slat/slot',text:'Um dispositivo de bordo de ataque que ajuda a retardar a separação do escoamento permite, em geral:',options:['operar a ângulos de ataque maiores antes do estol','reduzir a sustentação máxima','eliminar a camada limite','impedir qualquer aumento de arrasto'],correctIndex:0,explanation:'Slats/slots energizam o escoamento sobre a asa e adiam a separação.',difficulty:3,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-020',subject:'Teoria de Voo',chapter:'10',topic:'Spoiler',text:'Quando um spoiler é defletido sobre a asa, o efeito aerodinâmico esperado é:',options:['redução da sustentação e aumento do arrasto','aumento da sustentação e redução do arrasto','aumento simultâneo de sustentação e tração','redução simultânea de peso e arrasto'],correctIndex:0,explanation:'Spoilers perturbam o escoamento sobre a asa, diminuindo sustentação e aumentando arrasto.',difficulty:2,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-021',subject:'Teoria de Voo',chapter:'4',topic:'Arfagem',text:'A arfagem ocorre em torno de qual eixo e é controlada principalmente por qual superfície?',options:['eixo lateral; profundor','eixo vertical; leme','eixo longitudinal; ailerons','eixo lateral; ailerons'],correctIndex:0,explanation:'Arfagem é a rotação em torno do eixo lateral, comandada pelo profundor.',difficulty:2,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'},
{id:'EXT-HMMA-TV-022',subject:'Teoria de Voo',chapter:'4',topic:'Rolamento',text:'O rolamento de uma aeronave acontece em torno do:',options:['eixo longitudinal','eixo vertical','eixo lateral','eixo de incidência'],correctIndex:0,explanation:'Rolamento é a rotação em torno do eixo longitudinal.',difficulty:1,isCalculation:false,bank:'external-adapted',source:'Hangar MMA — Aerodinâmica • conceito adaptado, não literal'}
];

// V17 — NAV: dois novos manuais enviados pelo utilizador.
window.NAV_PDF_META={
  version:17,
  sources:[
    {id:'MONTEIRO-NAV-PP',title:'Nova Síntese da Navegação Aérea — 1ª Parte — Piloto Privado',author:'Manoel Agostinho Monteiro',file:'books/NAV_Nova_Sintese_Monteiro.pdf',subject:'Navegação'},
    {id:'ROOS-NAV-PP',title:'Navegação Visual e Estimada — Piloto Privado',author:'Titus Roos',file:'books/NAV_Visual_Estimada_Roos.pdf',subject:'Navegação'}
  ],
  classification:'NAV — Navegação Aérea (Piloto Privado)',
  policy:'Questões do simulado transcritas somente quando leitura e gabarito estavam inequívocos; demais itens são adaptações originais baseadas na teoria dos dois manuais.'
};
window.BOOK_CATALOG=window.BOOK_CATALOG||{};
window.BOOK_CATALOG['NAV-MONTEIRO']={title:'Nova Síntese da Navegação Aérea — PP (Monteiro)',file:'books/NAV_Nova_Sintese_Monteiro.pdf',direct:0,derived:25};
window.BOOK_CATALOG['NAV-ROOS']={title:'Navegação Visual e Estimada — PP (Roos)',file:'books/NAV_Visual_Estimada_Roos.pdf',direct:15,derived:25};

window.EXTERNAL_QUESTIONS.push(
{id:'NAV-ROOS-P1-02',subject:'Navegação',chapter:'1',topic:'Terra',text:'O círculo máximo que divide a Terra nos hemisférios Norte e Sul, com plano passando pelo centro e perpendicular ao eixo terrestre, chama-se:',options:['círculo menor','paralelo','meridiano','Equador'],correctIndex:3,explanation:'Gabarito da Prova 1: alternativa D.',difficulty:2,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 2'},
{id:'NAV-ROOS-P1-03',subject:'Navegação',chapter:'1',topic:'Forma da Terra',text:'Para efeito dos cálculos usuais de navegação, a forma da Terra é considerada:',options:['elipsoide de revolução','levemente achatada nos polos','irregular','esfera'],correctIndex:3,explanation:'Gabarito da Prova 1: alternativa D.',difficulty:1,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 3'},
{id:'NAV-ROOS-P1-04',subject:'Navegação',chapter:'1',topic:'Antimeridiano',text:'O antimeridiano do meridiano de longitude 120°E é:',options:['060°E','060°W','150°E','150°W'],correctIndex:1,explanation:'Gabarito da Prova 1: alternativa B.',difficulty:2,isCalculation:true,bank:'source-direct',source:'Titus Roos — Prova 1, questão 4'},
{id:'NAV-ROOS-P1-05',subject:'Navegação',chapter:'2',topic:'Latitude',text:'O arco de meridiano compreendido entre o Equador e o paralelo de um lugar determina a:',options:['latitude','longitude','diferença de latitude','diferença de longitude'],correctIndex:0,explanation:'Gabarito da Prova 1: alternativa A.',difficulty:1,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 5'},
{id:'NAV-ROOS-P1-06',subject:'Navegação',chapter:'4',topic:'Unidades',text:'Para cálculos de navegação, distâncias em cartas e velocidades devem estar preferencialmente, respectivamente, em:',options:['km e kt','NM e mph','km e km/h','NM e kt'],correctIndex:3,explanation:'Gabarito da Prova 1: alternativa D.',difficulty:1,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 6'},
{id:'NAV-ROOS-P1-07',subject:'Navegação',chapter:'7',topic:'Altimetria',text:'O ajuste altimétrico utilizado normalmente nas operações de pouso e decolagem é:',options:['QNH','QFE','QNE','QFF'],correctIndex:0,explanation:'Gabarito da Prova 1: alternativa A.',difficulty:2,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 7'},
{id:'NAV-ROOS-P1-08',subject:'Navegação',chapter:'7',topic:'Instrumentos',text:'Qual instrumento indica ao piloto a razão de subida ou descida da aeronave?',options:['DME','RMI','climb/VSI','altímetro'],correctIndex:2,explanation:'Gabarito da Prova 1: alternativa C.',difficulty:1,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 8'},
{id:'NAV-ROOS-P1-09',subject:'Navegação',chapter:'5',topic:'Rota',text:'A trajetória percorrida ou a percorrer por uma aeronave sobre a superfície terrestre chama-se:',options:['rota','proa','caminho','rumo'],correctIndex:0,explanation:'Gabarito da Prova 1: alternativa A.',difficulty:1,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 9'},
{id:'NAV-ROOS-P1-10',subject:'Navegação',chapter:'9',topic:'Correção de deriva',text:'O ângulo de correção de deriva é formado entre a proa da aeronave e:',options:['Norte verdadeiro','Norte magnético','rumo/rota a seguir','linha Norte-Sul da bússola'],correctIndex:2,explanation:'Gabarito da Prova 1: alternativa C.',difficulty:2,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 10'},
{id:'NAV-ROOS-P1-11',subject:'Navegação',chapter:'6',topic:'Magnetismo',text:'Linhas traçadas nas cartas que unem pontos de mesma declinação magnética chamam-se:',options:['isoclínicas','isóbaras','isotérmicas','isogônicas'],correctIndex:3,explanation:'Gabarito da Prova 1: alternativa D.',difficulty:1,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 11'},
{id:'NAV-ROOS-P1-12',subject:'Navegação',chapter:'6',topic:'Bússola',text:'O ângulo entre o meridiano magnético e a linha Norte-Sul indicada pela bússola denomina-se:',options:['proa bússola','proa magnética','desvio de bússola','declinação magnética'],correctIndex:2,explanation:'Gabarito da Prova 1: alternativa C.',difficulty:2,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 12'},
{id:'NAV-ROOS-P1-13',subject:'Navegação',chapter:'8',topic:'Fusos horários',text:'Um fuso horário teórico abrange uma faixa de:',options:['15° de latitude','15° de longitude','7°30′ de latitude','7°30′ de longitude'],correctIndex:1,explanation:'Gabarito da Prova 1: alternativa B.',difficulty:1,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 13'},
{id:'NAV-ROOS-P1-17',subject:'Navegação',chapter:'5',topic:'Proa verdadeira',text:'O ângulo formado entre o meridiano verdadeiro e o eixo longitudinal da aeronave chama-se:',options:['proa magnética','proa bússola','proa verdadeira','declinação magnética'],correctIndex:2,explanation:'Gabarito da Prova 1: alternativa C.',difficulty:1,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 17'},
{id:'NAV-ROOS-P1-18',subject:'Navegação',chapter:'5',topic:'Representação terrestre',text:'A representação gráfica da superfície terrestre desenvolvida num plano, sem grandes detalhes de projeção, é denominada:',options:['mapa','visão','projeção','carta'],correctIndex:0,explanation:'Gabarito da Prova 1: alternativa A.',difficulty:2,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 18'},
{id:'NAV-ROOS-P1-19',subject:'Navegação',chapter:'5',topic:'Projeção gnomônica',text:'Numa projeção gnomônica, as linhas de projeção têm origem no:',options:['infinito','ponto oposto','centro da Terra','ponto tangente'],correctIndex:2,explanation:'Gabarito da Prova 1: alternativa C.',difficulty:3,isCalculation:false,bank:'source-direct',source:'Titus Roos — Prova 1, questão 19'},
{id:'NAV-ROOS-P1-20',subject:'Navegação',chapter:'4',topic:'Conversões',text:'Convertendo 85 km para milhas terrestres e milhas náuticas, os valores aproximados são, respectivamente:',options:['46 e 53','53 e 46','136 e 157','157 e 136'],correctIndex:1,explanation:'Gabarito da Prova 1: alternativa B.',difficulty:2,isCalculation:true,bank:'source-direct',source:'Titus Roos — Prova 1, questão 20'}
);

const NAV_THEORY_V17=[
['Processos de navegação','Na navegação visual, a orientação é obtida principalmente por:',['referências visíveis na superfície','somente ondas de rádio','somente satélites','cálculo astronômico'],0,'Roos'],
['Navegação estimada','Na navegação estimada, o conjunto básico citado para condução é:',['bússola, velocímetro e relógio','altímetro, DME e ADF','VOR, GPS e transponder','bússola, radar e rádio'],0,'Roos'],
['Círculo máximo','Um círculo máximo resulta de um plano que:',['passa pelo centro da esfera','não passa pelo centro','é sempre paralelo ao Equador','toca a esfera em um ponto'],0,'Roos/Monteiro'],
['Círculo menor','Um círculo menor é formado por plano que:',['não passa pelo centro da esfera','sempre contém o eixo polar','divide a Terra em duas partes iguais','é perpendicular ao Equador'],0,'Roos/Monteiro'],
['Equador','O Equador é:',['o único paralelo que é círculo máximo','um meridiano de origem','um círculo menor','um semicírculo máximo'],0,'Roos/Monteiro'],
['Meridianos','Os meridianos são:',['semicírculos máximos limitados pelos polos','círculos menores paralelos ao Equador','linhas que nunca convergem','círculos máximos paralelos entre si'],0,'Roos/Monteiro'],
['Coordenadas','A ordem convencional para informar coordenadas geográficas é:',['latitude e longitude','longitude e latitude','rumo e proa','DLA e DLO'],0,'Roos/Monteiro'],
['Latitude','A latitude é medida sobre:',['arco de meridiano','arco de paralelo','linha isogônica','rota loxodrômica'],0,'Roos/Monteiro'],
['Longitude','A longitude é medida sobre:',['arco de paralelo','arco de meridiano','linha isobárica','círculo vertical'],0,'Roos/Monteiro'],
['Latitude','Os valores de latitude variam de:',['0° a 90° N ou S','0° a 180° E ou W','0° a 360°','90° a 180°'],0,'Roos/Monteiro'],
['Longitude','Os valores de longitude variam de:',['0° a 180° E ou W','0° a 90° N ou S','0° a 360° N','90° a 270°'],0,'Roos/Monteiro'],
['DLA','Para duas latitudes no mesmo hemisfério, a DLA é obtida, em regra, por:',['subtração','soma','multiplicação','divisão'],0,'Roos/Monteiro'],
['DLA','Para duas latitudes em hemisférios diferentes, a DLA é obtida, em regra, por:',['soma','subtração','média aritmética','regra de três'],0,'Roos/Monteiro'],
['DLO','Para duas longitudes de mesmo nome, a DLO é obtida, em regra, por:',['subtração','soma','produto','média'],0,'Monteiro'],
['DLO','Para longitudes de nomes contrários, calcula-se inicialmente a DLO por:',['soma','subtração','divisão por dois','conversão em latitude'],0,'Monteiro'],
['Antimeridiano','O antimeridiano está separado do meridiano considerado por:',['180°','90°','360°','15°'],0,'Monteiro'],
['Unidades angulares','Um grau corresponde a:',['60 minutos de arco','100 minutos de arco','60 segundos de arco','15 minutos de arco'],0,'Roos/Monteiro'],
['Unidades angulares','Um minuto de arco corresponde a:',['60 segundos de arco','100 segundos','15 segundos','360 segundos'],0,'Roos/Monteiro'],
['Rotação da Terra','Vista do Polo Norte, a rotação da Terra ocorre no sentido:',['anti-horário','horário','Norte-Sul','Sul-Norte'],0,'Roos'],
['Pontos geográficos','O cruzamento de um paralelo com um meridiano define:',['um ponto geográfico','um fuso horário','uma isogônica','uma rota'],0,'Roos'],
['Vento','Quando há vento, a correção de deriva é usada para:',['manter a trajetória/rota desejada','alterar a latitude média','corrigir o altímetro','converter IAS em TAS'],0,'Monteiro'],
['Triângulo do vento','No triângulo de velocidades, a velocidade no solo resulta da combinação da velocidade aerodinâmica com:',['o vento','a declinação magnética','a altitude pressão','o QNH'],0,'Monteiro'],
['Navegação','Navegar implica determinar continuamente dois elementos fundamentais:',['localização e orientação','peso e balanceamento','potência e mistura','altitude e temperatura apenas'],0,'Roos'],
['Paralelos','Exceto o Equador, os paralelos são:',['círculos menores','círculos máximos','semicírculos máximos','meridianos'],0,'Roos'],
['Greenwich','O meridiano de Greenwich corresponde à longitude:',['000°','090°E','180°','090°W'],0,'Roos/Monteiro']
];
NAV_THEORY_V17.forEach((x,i)=>window.EXTERNAL_QUESTIONS.push({id:'NAV-THEORY-V17-'+String(i+1).padStart(3,'0'),subject:'Navegação',chapter:String(i<10?1:i<18?2:9),topic:x[0],text:x[1],options:x[2],correctIndex:x[3],explanation:'Questão adaptada da teoria dos dois novos manuais de Navegação.',difficulty:i%3+1,isCalculation:/DLA|DLO|Antimeridiano|Unidades/.test(x[0]),bank:'source-derived',source:'V17 • '+x[4]}));
